version: '2'
services:
  weather_input:
    image: weather_input
    ports:
      - "8087:8087"
    volumes:
      # Add route to the client config
      - \Users\micha\git\templates-sources:/root/.ba/weather
    networks:
      spnet:
